// json2define
// lib/index.js


/**
 * Module dependencies.
 */
var fs = require('fs');
var pkg = require('../package.json');


function json2define() {
  this.root = '';
  this.data;
  this.uppercase = true;
  this.linebreak = '\n';
}

module.exports = json2define;

json2define.prototype.setRoot = function(root) {
  this.root = root;
};

json2define.prototype.setData = function(data) {
  this.data = data;
};

json2define.prototype.setUppercase = function(uppercase) {
  this.uppercase = uppercase;
};

json2define.prototype.getDefineString = function(name, value) {
  if (this.uppercase === true) name = name.toUpperCase();
  var str = '#define ';
  if (this.root !== '') str += this.root+'_';
  str += name+' "'+value+'"';
  return str;
};

json2define.prototype.getFileHead = function() {
  var str = '//'+this.linebreak;
  str += '// This File was generated by '+pkg.name+this.linebreak;
  str += '// '+pkg.repository.url+this.linebreak;
  str += '//'+this.linebreak;
  str += '// Date: '+new Date()+this.linebreak;
  str += '//'+this.linebreak;
  return str;
};

json2define.prototype.readFileSync = function(filename) {
  var file = fs.readFileSync(filename, 'utf-8');
  this.data = JSON.parse(file);
};

json2define.prototype.generate = function() {
  var str = this.getFileHead()+this.linebreak;
  str += this.parseObject(this.data);
  return str;
};

json2define.prototype.parseObject = function(obj, beginStr) {
  if (beginStr === undefined) beginStr = '';
  else beginStr += '_';
  var str = '';
  for(i in obj) {
    if (typeof obj[i] === 'object') {
      //str += '// object '+i+this.linebreak;
      str += this.parseObject(obj[i], i);
    }
    else {
      str += this.getDefineString(beginStr+i, obj[i])+this.linebreak;
    }
    //console.log(i+' '+this.data[i]);
  }
  return str;
};
